require "lua.api.common"
require "lua.api.blizzard"
require "lua.api.KK_japi"
-- require "lua.api.deBug"

require "lua.Base.Time"
require "lua.Base.Sync"
require "lua.Base.Player"
require "lua.Base.Sound"
require "lua.Base.Texture"

require "lua.Base.Lightning"
require "lua.Base.Weather"
require "lua.Base.Camera"
require "lua.Base.CameraScroll"
require "lua.Base.Event"
require "lua.Base.TextTag"
require "lua.Base.Rect"
require "lua.Base.Unit"
require "lua.Base.Group"
require "lua.Base.Hero"
require "lua.Base.Skill"
require "lua.Base.Item"
require "lua.Base.Frame"
require "lua.Base.Pool"
require "lua.Base.Obj"
require "lua.Base.Dialog"
require "lua.Base.Quest"
require "lua.Base.Terrain"
require "lua.Base.Visibility"
require "lua.Base.SystemMessage"
require "lua.Base.Effect"
require "lua.Base.Multiboard"

-- 底层：游戏资源泄露检测（默认开启，UI TXT 播报）
require "lua.api.LeakDetect"

